
name: Spawn Release Canidate 🧪

on:
  push: 
    branches:
      - candidate

jobs:

  increment:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          ref: candidate
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Install UV
        uses: astral-sh/setup-uv@v7
      
      - name: Dry Run Version Increment
        run: |
          uv version --bump rc --dry-run

      - name: Version Increment
        run: |
          uv version --bump rc

      - name: Verify Version Changed
        run: git diff --exit-code pyproject.toml || echo "Version updated successfully"

      - name: Increment Release Candidate Version
        id: version
        shell: bash
        run: |
          VERSION=$( uv version --short)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Commit & Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: candidate
          commit_message: "chore: bump rc version to ${{ steps.version.outputs.version }}"
          file_pattern: pyproject.toml
          
  build:
    name: Build Distribution 📦; Cache Distribution ⬆️
    needs: increment
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: success()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ref: candidate

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Build Package
        run: uv build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-canidate-python-package-distributions
          path: dist/
          retention-days: 3

  release:
    permissions: # Read more at : https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      contents: write
    name: Create Branch
    needs: increment
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ref: candidate
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Create release branch from version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout candidate
          git checkout -b release@v$(uv version --short)
          git push origin release@v$(uv version --short)

  hotfix:
    permissions: # Read more at : https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      contents: write
    name: Create Branch
    needs: release
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ref: candidate
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Create release branch from version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout candidate
          git checkout -b v/hotfix/$(uv version --short)
          git push origin v/hotfix/$(uv version --short)
