name: Spawn Stable Branch 🗒️

on: 
  pull_request:
    branches: beta
    types: closed

permissions: write-all

jobs:

    increment:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code
          uses: actions/checkout@v6
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
  
        - name: Setup UV
          uses: astral-sh/setup-uv@v7

        - name: Dry Run Version Increment
          run: |
            uv version --bump beta --dry-run
  
        - name: Version Increment
          run: |
            uv version --bump beta
  
        - name: Verify Version Changed
          run: git diff --exit-code pyproject.toml || echo "Version updated successfully"
  
        - name: Increment Beta Version
          id: version
          shell: bash
          run: |
            VERSION=$(uv version --short)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
  
        - name: Commit & Push Version Change
          uses: stefanzweifel/git-auto-commit-action@v7
          with:
            branch: beta
            commit_message: "chore: bump beta version to ${{ steps.version.outputs.version }}"
            file_pattern: pyproject.toml

        - name: Create Git Tag
          run: |
            git tag v${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
            git push origin v${{ steps.version.outputs.version }}

        

    release:
      permissions: # Read more at : https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
        contents: write
      name: Create Branch
      needs: increment
      runs-on: ubuntu-latest
      steps:
      
        - name: Checkout Code
          uses: actions/checkout@v6
          with:
            ref: beta
            token: ${{ secrets.GITHUB_TOKEN }}
    
        - name: Setup UV
          uses: astral-sh/setup-uv@v7

        - name: Get Stable Version
          id: version
          run: echo "version=$(uv version --short)" >> $GITHUB_OUTPUT
            
        - name: Create Branch
          id: create_branch
          uses: lablnet/create-branch-from-tag@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: v${{ steps.version.outputs.version }}
            owner: ${{ github.repository_owner }} # https://docs.github.com/en/actions/learn-github-actions/contexts#example-contents-of-the-github-context
            repo: ${{ github.event.repository.name }} # https://www.reddit.com/r/github/comments/tjkj6f/get_repo_name_on_github_actions_without_owner/
  
